name: Compile
on:
  push:
    branches: [ master ]
    paths:
      - 'src/**.cs'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**.cs'
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: setup msbuild
        uses: microsoft/setup-msbuild@v1.1

      - name: checkout repo
        uses: actions/checkout@v2

      - name: run package restore
        run: nuget restore Garfield.csproj
      
      - name: build makeres
        run: msbuild makeres.csproj -t:Build
        working-directory: resource/
      
      - name: generate resources
        run: makeres
        working-directory: resource/

      - name: build garfsharp
        run: msbuild Garfield.csproj

      - name: artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: GarfSharp
          path: |
            bin/
